// Code generated by go run ./cmd/compozy-codegen sdk-contracts-go. DO NOT EDIT.

package contracts

import (
	"encoding/json"
	"time"
)

type PermissionRequestPayload struct {
	Event          HookEvent          `json:"event"`
	Timestamp      time.Time          `json:"timestamp"`
	ProfileID      string             `json:"profile_id,omitempty"`
	SessionID      string             `json:"session_id,omitempty"`
	SessionName    string             `json:"session_name,omitempty"`
	SessionType    string             `json:"session_type,omitempty"`
	AgentName      string             `json:"agent_name,omitempty"`
	WorkspaceID    string             `json:"workspace_id,omitempty"`
	Workspace      string             `json:"workspace,omitempty"`
	WorktreeID     string             `json:"worktree_id,omitempty"`
	ACPSessionID   string             `json:"acp_session_id,omitempty"`
	State          string             `json:"state,omitempty"`
	SoulSnapshotID string             `json:"soul_snapshot_id,omitempty"`
	SoulDigest     string             `json:"soul_digest,omitempty"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	TurnID         string             `json:"turn_id,omitempty"`
	RequestID      string             `json:"request_id,omitempty"`
	Action         string             `json:"action,omitempty"`
	Resource       string             `json:"resource,omitempty"`
	Decision       string             `json:"decision,omitempty"`
	DecisionClass  string             `json:"decision_class,omitempty"`
	ToolInput      json.RawMessage    `json:"tool_input,omitempty"`
	ToolCall       PermissionToolCall `json:"tool_call"`
	Options        []PermissionOption `json:"options,omitempty"`
}

type PermissionResolutionPayload struct {
	Event          HookEvent          `json:"event"`
	Timestamp      time.Time          `json:"timestamp"`
	ProfileID      string             `json:"profile_id,omitempty"`
	SessionID      string             `json:"session_id,omitempty"`
	SessionName    string             `json:"session_name,omitempty"`
	SessionType    string             `json:"session_type,omitempty"`
	AgentName      string             `json:"agent_name,omitempty"`
	WorkspaceID    string             `json:"workspace_id,omitempty"`
	Workspace      string             `json:"workspace,omitempty"`
	WorktreeID     string             `json:"worktree_id,omitempty"`
	ACPSessionID   string             `json:"acp_session_id,omitempty"`
	State          string             `json:"state,omitempty"`
	SoulSnapshotID string             `json:"soul_snapshot_id,omitempty"`
	SoulDigest     string             `json:"soul_digest,omitempty"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	TurnID         string             `json:"turn_id,omitempty"`
	RequestID      string             `json:"request_id,omitempty"`
	Action         string             `json:"action,omitempty"`
	Resource       string             `json:"resource,omitempty"`
	Decision       string             `json:"decision,omitempty"`
	DecisionClass  string             `json:"decision_class,omitempty"`
	ToolInput      json.RawMessage    `json:"tool_input,omitempty"`
	ToolCall       PermissionToolCall `json:"tool_call"`
}

type PermissionResolvedPatch struct{}

type PermissionResolvedPayload struct {
	Event          HookEvent          `json:"event"`
	Timestamp      time.Time          `json:"timestamp"`
	ProfileID      string             `json:"profile_id,omitempty"`
	SessionID      string             `json:"session_id,omitempty"`
	SessionName    string             `json:"session_name,omitempty"`
	SessionType    string             `json:"session_type,omitempty"`
	AgentName      string             `json:"agent_name,omitempty"`
	WorkspaceID    string             `json:"workspace_id,omitempty"`
	Workspace      string             `json:"workspace,omitempty"`
	WorktreeID     string             `json:"worktree_id,omitempty"`
	ACPSessionID   string             `json:"acp_session_id,omitempty"`
	State          string             `json:"state,omitempty"`
	SoulSnapshotID string             `json:"soul_snapshot_id,omitempty"`
	SoulDigest     string             `json:"soul_digest,omitempty"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	TurnID         string             `json:"turn_id,omitempty"`
	RequestID      string             `json:"request_id,omitempty"`
	Action         string             `json:"action,omitempty"`
	Resource       string             `json:"resource,omitempty"`
	Decision       string             `json:"decision,omitempty"`
	DecisionClass  string             `json:"decision_class,omitempty"`
	ToolInput      json.RawMessage    `json:"tool_input,omitempty"`
	ToolCall       PermissionToolCall `json:"tool_call"`
}

type PermissionSet struct {
	Tools           []string `json:"tools,omitempty"`
	Skills          []string `json:"skills,omitempty"`
	MCPServers      []string `json:"mcp_servers,omitempty"`
	WorkspacePaths  []string `json:"workspace_paths,omitempty"`
	NetworkChannels []string `json:"network_channels,omitempty"`
	SandboxProfiles []string `json:"sandbox_profiles,omitempty"`
}

type PermissionToolCall struct {
	ID        string         `json:"id,omitempty"`
	Kind      string         `json:"kind,omitempty"`
	Title     string         `json:"title,omitempty"`
	Status    string         `json:"status,omitempty"`
	Locations []ToolLocation `json:"locations,omitempty"`
}

type PersistenceHealth struct {
	Status             string `json:"status"`
	GlobalDBSizeBytes  int64  `json:"global_db_size_bytes"`
	SessionDBSizeBytes int64  `json:"session_db_size_bytes"`
}

type PickFilesEffect struct {
	Directories bool `json:"directories,omitempty"`
}

type Priority string

type ProbeResult struct {
	AgentName  string    `json:"agent_name,omitempty"`
	Provider   string    `json:"provider,omitempty"`
	Command    string    `json:"command,omitempty"`
	Executable string    `json:"executable,omitempty"`
	Status     string    `json:"status"`
	Error      string    `json:"error,omitempty"`
	CheckedAt  time.Time `json:"checked_at"`
	DurationMS int64     `json:"duration_ms"`
}

type ProfileLens struct {
	ID   ProfileLensID `json:"profile_lens_id"`
	Name string        `json:"profile_name"`
}

type ProfileLensID string

type PromptDelivery string

type PromptMode string

type PromptPatch struct {
	Deny          bool           `json:"deny,omitempty"`
	DenyReason    string         `json:"deny_reason,omitempty"`
	Prompt        *string        `json:"prompt,omitempty"`
	ContextBlocks []ContextBlock `json:"context_blocks,omitempty"`
}

type PromptPayload struct {
	Event          HookEvent      `json:"event"`
	Timestamp      time.Time      `json:"timestamp"`
	ProfileID      string         `json:"profile_id,omitempty"`
	SessionID      string         `json:"session_id,omitempty"`
	SessionName    string         `json:"session_name,omitempty"`
	SessionType    string         `json:"session_type,omitempty"`
	AgentName      string         `json:"agent_name,omitempty"`
	WorkspaceID    string         `json:"workspace_id,omitempty"`
	Workspace      string         `json:"workspace,omitempty"`
	WorktreeID     string         `json:"worktree_id,omitempty"`
	ACPSessionID   string         `json:"acp_session_id,omitempty"`
	State          string         `json:"state,omitempty"`
	SoulSnapshotID string         `json:"soul_snapshot_id,omitempty"`
	SoulDigest     string         `json:"soul_digest,omitempty"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	TurnID         string         `json:"turn_id,omitempty"`
	InputClass     string         `json:"input_class,omitempty"`
	Prompt         string         `json:"prompt,omitempty"`
	ContextBlocks  []ContextBlock `json:"context_blocks,omitempty"`
}

type PromptRuntimeSelectionPayload struct {
	Provider        string                    `json:"provider"`
	Model           string                    `json:"model,omitempty"`
	ReasoningEffort Effort                    `json:"reasoning_effort,omitempty"`
	Speed           Speed                     `json:"speed,omitempty"`
	ACPOptions      []AgentACPOptionSelection `json:"acp_options,omitempty"`
}

type ProviderModelConfigurationPayload struct {
	ReasoningEffort *Effort `json:"reasoning_effort,omitempty"`
	Fast            *bool   `json:"fast,omitempty"`
	Thinking        *bool   `json:"thinking,omitempty"`
}

type ProviderModelListResponse struct {
	Models []ProviderModelPayload `json:"models"`
}

type ProviderModelPayload struct {
	ProviderID             string                              `json:"provider_id"`
	ModelID                string                              `json:"model_id"`
	Default                bool                                `json:"default"`
	DisplayName            string                              `json:"display_name,omitempty"`
	Sources                []ModelCatalogSourceRefPayload      `json:"sources"`
	Available              *bool                               `json:"available"`
	AvailabilityState      string                              `json:"availability_state"`
	Startable              bool                                `json:"startable"`
	StartBlockedReason     string                              `json:"start_blocked_reason,omitempty"`
	Stale                  bool                                `json:"stale"`
	RefreshedAt            string                              `json:"refreshed_at,omitempty"`
	ContextWindow          *int64                              `json:"context_window,omitempty"`
	MaxInputTokens         *int64                              `json:"max_input_tokens,omitempty"`
	MaxOutputTokens        *int64                              `json:"max_output_tokens,omitempty"`
	SupportsTools          *bool                               `json:"supports_tools,omitempty"`
	SupportsReasoning      *bool                               `json:"supports_reasoning,omitempty"`
	ReasoningEfforts       []Effort                            `json:"reasoning_efforts,omitempty"`
	DefaultReasoningEffort *Effort                             `json:"default_reasoning_effort,omitempty"`
	ConfigOptions          []SessionConfigOptionPayload        `json:"config_options,omitempty"`
	Configurations         []ProviderModelConfigurationPayload `json:"configurations,omitempty"`
	Cost                   *ModelCatalogCostPayload            `json:"cost,omitempty"`
	Curated                bool                                `json:"curated"`
	Deprecated             bool                                `json:"deprecated"`
	Hidden                 bool                                `json:"hidden"`
	Featured               bool                                `json:"featured"`
	ReleaseDate            string                              `json:"release_date,omitempty"`
	ReasoningSource        ReasoningSource                     `json:"reasoning_source,omitempty"`
	LastError              string                              `json:"last_error,omitempty"`
}

type ProviderModelRefreshResponse struct {
	Sources []ModelCatalogSourceStatusPayload `json:"sources"`
	Error   string                            `json:"error,omitempty"`
}

type ProviderModelStatusResponse struct {
	Sources []ModelCatalogSourceStatusPayload `json:"sources"`
}

type ReasonCode string

type ReasoningSource string
